### ISSUE TITLE
Empty database should be initialised when OMERO.server already installed

### ISSUE THREAD

**Issue by manics** [openmicroscopy/ansible-role-omero-server#13]
For example, if you run this playbook PostgreSQL will be installed, OMERO.server will be downloaded and symlinked, but the database initialisation will fail because it can't be accessed due to a missing
`postgresql_server_listen: "'*'"`.
```
- hosts: omero-database
  roles:
    - role: openmicroscopy.postgresql
  vars:
    postgresql_users_databases:
    - user: omero
      password: omero
      databases: [omero]
    postgresql_version: "9.6"

- hosts: omero-server
  roles:
    - role: openmicroscopy.omero-server
    - role: openmicroscopy.omero-web
  vars:
    omero_server_dbhost: "{{ hostvars['omero-database'].ansible_eth0.ipv4.address }}"
```

 If this line is added and the playbook rerun the role will fail- OMERO.server appears to be installed so the role attempts to start it, which fails since the omero database exists but is empty.
