### ISSUE TITLE
Adding a new setting to bin/omero config will change order

### ISSUE THREAD

**Issue by pwalczysko** [openmicroscopy/ansible-role-omero-server#25]
After I have played my playbook, I got in the output
```
TASK [openmicroscopy.omero-server : omero server | configuration 00-omero-server.omero] **************************************************************
--- before: /opt/omero/server/config/00-omero-server.omero
+++ after: /var/folders/j3/9sf00sjs4kng7djn76m0_grh4d75r0/T/tmp_DeAOt/00-omero-server-omero.j2
@@ -11,6 +11,8 @@
 
 # Additional custom options
 config set -- omero.jvmcfg.percent.indexer 20
+config set -- omero.fs.importUsers 'fm1;fm2'
 config set -- omero.db.poolsize 50
+config set -- omero.jvmcfg.percent.blitz 50
+config set -- omero.fs.watchDir '/home/fm1;/home/fm2'
 config set -- omero.jvmcfg.percent.pixeldata 20
-config set -- omero.jvmcfg.percent.blitz 50
```
My workflow was to add 2 lines (the ``omero.fs....`` lines, see an excerpt from my playbook below) into my playbook before I played it.

```
    omero_server_config_set:
      omero.fs.importUsers: "fm1;fm2"
      omero.fs.watchDir: "/home/fm1;/home/fm2"
      omero.db.poolsize: 50
      omero.jvmcfg.percent.blitz: 50
      omero.jvmcfg.percent.indexer: 20
      omero.jvmcfg.percent.pixeldata: 20
```
